### ISSUE TITLE
Wrong serial numer of ath-6k-tl inverter

### ISSUE THREAD

**Issue by pierpaolo1972** [wilds/hass-atonstorage#1]
hi I have an Aton ATH-6K-TL inverter, I have installed the integration. When I enter the serial number it gives me an error. the S/N is something like 014F with other numbers. That's 15 characters in total. where am i wrong?

**Comment by wilds** [comment]
Hi @pierpaolo1972 
can you try the new version? I think yout error is related to #2

**Comment by pierpaolo1972** [comment]
Thanks for the update.
I uploaded version 1.0.2 but when I install the integration it gives me an error.
 "Impossibile caricare il flusso di configurazione: Failed dependencies httpx" 
I've tried uninstalling everything and reinstalling but it doesn't work. I don't know if it's my problem.

**Comment by wilds** [comment]
Sorry. I rebuild the version. Now it should work

**Comment by pierpaolo1972** [comment]
Ok, now it no longer gives the "Failed dependencies httpx" error. Load it form but if I put my data it doesn't go on. "[%key:common::config_flow::error::unknown%]"
Name and password are those used to access the site. the serial number are the 12 characters that I find on the aton page and on the inverter. but it doesn't work

**Comment by wilds** [comment]
I think it's fixed now

**Comment by pierpaolo1972** [comment]
It's working. gooood job. Grande, complimenti !! thank you so much for your time and work!!!

**Comment by wilds** [comment]
Grazie!
