### ISSUE TITLE
"Istant" sensors not available in Energy Management ( Home Assistant )

### ISSUE THREAD

**Issue by ps121988** [wilds/hass-atonstorage#10]
Hello Dev

Many Thanks for your job.
When i've tried to configure Energy Management using Instant* sensors ( image1 ) , they are not available ( image2 ).
Did i miss something ?

Bye 

Paolo

![Image1](https://user-images.githubusercontent.com/127797311/224936297-6ca20a08-4348-4b8d-b238-0a1c98596847.jpg)
![image2](https://user-images.githubusercontent.com/127797311/224936302-52f20798-6ff0-494a-8d58-347d6558bae3.jpg)

**Comment by wilds** [comment]
Ho Paolo,
for the correct configuration of the energy dashboard you have to use the "battery charged" and "battery discharged" sensors. Hassio will do the rest. 😉
