### ISSUE TITLE
Understanding different power sensors

### ISSUE THREAD

**Issue by tetionet** [wilds/hass-atonstorage#19]
Hi all, I don't know if it's an issue of the integration but I don't understand differences between power_grid, instant_power_grid, power_grid_input ad power_grid_output.
If I overlap them on a chart they seems to be not related to each other. I would like to understand which is the correct sensor to be used to automatically power on/off some non-essenstial equipment (basically I prefer to use a dehumidifier rather than sell energy)
![Screenshot_2023-11-15-19-10-16-42_c3a231c25ed346e59462e84656a70e50](https://github.com/wilds/hass-atonstorage/assets/75281515/33dc6b1d-3c09-4f3f-9ffa-d115b3948fe1)

**Comment by malcolmhm** [comment]
Hello,  I've only just started using this integration but I also use LucaPatarca/homeassistant_aton . I did wonder if the entities you're referring to are also in that integration but they aren't, they are also not in the .csv files that Aton have provided me from our installation. So just as mystified! (Not that it helps).
