### ISSUE TITLE
API Changes - Unauthorized error

### ISSUE THREAD

**Issue by marcoCasamento** [wilds/hass-atonstorage#2]
Hi, 
I've found that AtonStorage changed the way they expose their api and now it requests a valid PHP Session on the server to answer the requests.
after a POST to https://www.atonstorage.com/atonTC/index.php with body 
`username=USERNAME&password=PASSWORD&remember=on`
the server returns a Set-Cookie for PHPSESSID with a valid Session Id Value.
Subsequents calls must include that cookie to be authorized. 
Unfortunately I don't know the RestData() function used in controller.py and how it hanndle th cookies, if you can point me towards the docs of this method or even better a sample, I'd be happy to submit a PR.

**Comment by wilds** [comment]
Hi,
I was already working on it.
Unfortunately the RestData library wasn't the best choice. Now I migrated to httpx which handles cookies correctly.
