### ISSUE TITLE
Entities retrieved by the integration

### ISSUE THREAD

**Issue by malcolmhm** [wilds/hass-atonstorage#20]
Hello,

very pleased to find this integration as it is complementary to the one from LucaPatarca.  Especially that the string voltages and currents are exposed for our hybrid inverter.  However I don't see anything with regards to the battery status - eg the %ge charge of the battery.  Perhaps I should be computing that from some of the values we do get.  I do get this from the other integration however that integration seems to require me to re-enter the credentials often and reboot HA. It is scaled 0 - 100% though ATON's own app regards 20% charge as being the zero whereas we see the real percentage.

**Comment by nspickles** [comment]
@malcolmhm There is a state_of_battery sensor that shows the current battery % charge.

Or at least there is showing on the integration with system, I have the RA-Store3, which do you have?

**Comment by malcolmhm** [comment]
Hi, apologies only just spotted this. I've got the Gstore 4k - hybrid inverter, installed July this year. Thanks for your comment as it made me look further and found the relevant entity when looking at the integration from the settings/integrations etc- it just hadn't appeared automatically in the overview. So yes its there!
