### ISSUE TITLE
Historical data

### ISSUE THREAD

**Issue by nspickles** [wilds/hass-atonstorage#21]
I have has an Aton system installed since Feb 2023 and can go back to any date from install to now using the Aton App and see the stats for the day or month so the data must be stored with Aton somewhere.

Is there any way to retrieve this stored data and have it show up in Home Assistant as the stats/graphs available in HA are way better than the simple stats you can get in the app?

**Comment by malcolmhm** [comment]
> I have has an Aton system installed since Feb 2023 and can go back to any date from install to now using the Aton App and see the stats for the day or month so the data must be stored with Aton somewhere.
> 
> Is there any way to retrieve this stored data and have it show up in Home Assistant as the stats/graphs available in HA are way better than the simple stats you can get in the app?

I've asked for and received .csv files for requested months and some specific days via our support contact which have helped me to diagnose a solar string problem - its a shame we can't do it directly but with the installer level of access they can.
