### ISSUE TITLE
Daily energy sold incorrect

### ISSUE THREAD

**Issue by nspickles** [wilds/hass-atonstorage#22]
I have configured the energy dashboard in HA using the available sensors but the Daily Energy Sold sensor doesn't seem to be linked up to the energy export value, consequently I am showing no export to grid so the overall numbers are wrong. 

The Power grid input shows that export has occurred today but the daily energy sold value remains at 0.
The daily energy bought value is fine.

**Comment by nspickles** [comment]
Any update to this, still an issue in v1.04

**Comment by ps121988** [comment]
> I have configured the energy dashboard in HA using the available sensors but the Daily Energy Sold sensor doesn't seem to be linked up to the energy export value, consequently I am showing no export to grid so the overall numbers are wrong.
> 
> The Power grid input shows that export has occurred today but the daily energy sold value remains at 0. The daily energy bought value is fine.

Same problem too . Is it possible to solve the problem ? 
I'm available to upload any logs.

**Comment by wilds** [comment]
#29
