### ISSUE TITLE
Instant Grid Power

### ISSUE THREAD

**Issue by nspickles** [wilds/hass-atonstorage#23]
I can't see what the Instant Grid Power sensor relates to.

I would assume it was your instant power draw from the grid, but I am currently running from battery using 976w with no power from grid yet the Instant Grid Power value is sat at about 947w.

Can you confirm what actual value this sensor represents.

**Comment by mauriziosacca** [comment]
Update the integration and check again. In the last version I changed the behavior of several sensors, now it should give correct information

**Comment by nspickles** [comment]
Thanks, that issue seems to be sorted now, Instant Grid Power is now showing the actual grid power being drawn.
