### ISSUE TITLE
Charging

### ISSUE THREAD

**Issue by Majikmonke** [wilds/hass-atonstorage#26]
Hi

New to HA but looking to create a way to force charge the battery via automation.

Is this possible at all?

I have a smart plug that is linked to my meter so turns on when rates are cheap and off when they return to normal price so wondered if this was possible with the batteries?

**Comment by malcolmhm** [comment]
Hi,  I'm guessing you have an ATON battery or hybrid!  I've got a Gstore and this idea is potentially very interesting with developments on tarriffs particularly "Plunge" tariffs.   It would also be very useful with the grid saving events.  However I think ATON need to be persuaded to provide the "Hook" to enable this to happen one way or the other.  If other storage/ inverter vendors provide it then this would be a good argument. I suspect that trying to reverse engineer the way the app does forced charging may be somewhat tricky! I'd certainly like to see it implemented.
