### ISSUE TITLE
Valori differenti

### ISSUE THREAD

**Issue by FrancescoFdd5** [wilds/hass-atonstorage#30]
Ciao a me succede una cosa molto strana. Sto migrando integrazione da quella di LucaPatarca alla tua, ma i valori giornalieri mi vengono riportati in modo corretto all'interno dell'entità. Ma se messi nella plancia energia oppure in un plugin custom come quello nella foto diventano differenti. 

![image](https://github.com/wilds/hass-atonstorage/assets/12379812/76444545-a22f-410d-b558-a721d3f69fa6)
![image](https://github.com/wilds/hass-atonstorage/assets/12379812/7d1e2e5a-f3da-4163-9133-1d769043992c)

Io proprio non capisco quale sia il problema

EDIT:

I valori del grafico nel plugin custon sono gli stessi che mi vengono riportati nella plancia energia. 

Ovviamente con la vecchia integrazione sta funzionando tutto correttamente

**Comment by Fredxp73** [comment]
Guarda io ho lo stesso problema,  usanndo "Energy Flow control Card Plus" .... dal grafico sono sballati i dati, pero non e' un problema di dati presi dall integrazione, perche io sono conneso diretto con l' inverter  via modbus ... e pure i dati presi diretti da li se inserisco quei sensori me li riporta sballati, credo sia un bug di flow control plus....

**Comment by FrancescoFdd5** [comment]
> Guarda io ho lo stesso problema, usanndo "Energy Flow control Card Plus" .... dal grafico sono sballati i dati, pero non e' un problema di dati presi dall integrazione, perche io sono conneso diretto con l' inverter via modbus ... e pure i dati presi diretti da li se inserisco quei sensori me li riporta sballati, credo sia un bug di flow control plus....

Intanto grazie,
Volevo farti una domanda che non c’entra…
Come ti sei interfacciato in modbus?

Tornando in topic, la cosa che mi fa stranissimo che è avevo gli stessi valori sballati anche bella plancia energia e con l’altra integrazione va tutto bene

**Comment by maatx** [comment]
> Guarda io ho lo stesso problema, usanndo "Energy Flow control Card Plus" .... dal grafico sono sballati i dati, pero non e' un problema di dati presi dall integrazione, perche io sono conneso diretto con l' inverter via modbus ... e pure i dati presi diretti da li se inserisco quei sensori me li riporta sballati, credo sia un bug di flow control plus....

Interessa anche a me l'interfacciamento via modbus, si può evitare il cloud?
Grazie

**Comment by Fredxp73** [comment]
Ciao ,  devi acquistare la skeda dati da Aton, che pero' non la vende a privati, devi farla ordinare dal tuo elettricista\installatore di fiducia... montarla  e' una fesseria ... va inserita in uno slot....  non so quanto consigliarla pero' .... 
con la tabella registri che ti mandano loro,  ci sono meno sensori di quello che ottieni dall integrazione, 
alcuni valori ottenuti ,  tipo energia ceduta \ acquistata  sono indecifrabili (almeno x me) cioe' non trovo nessuna corrispondenza con il valore del cloud o tramite la pinza amperometrica della shelly

**Comment by wilds** [comment]
chiudo, non è un problema dell'integrazione
