### ISSUE TITLE
error installation

### ISSUE THREAD

**Issue by danielevsllsv** [wilds/hass-atonstorage#32]
[%key:common::config_flow::error::unknown%]

set the user,pass and serial this error appears

**Comment by Paolo7297** [comment]
I have the same error.
The log says:
```python
Traceback (most recent call last):
  File "/config/custom_components/atonstorage/config_flow.py", line 70, in async_step_user
    await self.async_set_unique_id(slugify(controller.serial_number))
                                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/atonstorage/controller.py", line 214, in serial_number
    return self.data["serialNumber"]
           ~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Ejl974** [comment]
Same error for me.

**Comment by Paolo7297** [comment]
I solved by going to aton website and login. If you have never changed credentials, it will ask for new password (to change default one), then it worked.

**Comment by marcels1990** [comment]
> I solved by going to aton website and login. If you have never changed credentials, it will ask for new password (to change default one), then it worked.

Confirmed, it also worked for me. Thank you very much
