### ISSUE TITLE
Variabili non disponibili dopo aggiornamento HA

### ISSUE THREAD

**Issue by FrancescoFdd5** [wilds/hass-atonstorage#34]
Da circa le 20:40 di oggi, 3 luglio 2024, tutte le variabili sono diventate "non disponibili". Ho provato a ricaricare l'integrazione e a riavviare Home Assistant, ma il problema persiste.

Dal log viewer vedo il seguente log:

`AtonStorageIntegrationSensor(
File "/config/custom_components/atonstorage/sensor.py", line 529, in __init__
  super().__init__()
TypeError: IntegrationSensor.__init__() missing 1 required keyword-only argument: 'max_sub_interval'
2024-07-03 23:42:31.456 WARNING (MainThread) [custom_components.atonstorage.controller] REST result could not be parsed as JSON
`

**Passaggi per riprodurre il problema:**

Aggiornare Home Assistant all'ultima versione disponibile.
Controllare lo stato delle variabili dell'integrazione AtonStorage.
Provare a ricaricare l'integrazione e riavviare Home Assistant.

**Comportamento atteso:**
Le variabili dovrebbero essere disponibili e funzionanti come prima dell'aggiornamento.

**Comportamento osservato:**
Tutte le variabili risultano "non disponibili" e i log riportano gli errori sopra indicati.

**Domanda:**
È un problema dell'integrazione a seguito dell'ultimo aggiornamento di Home Assistant rilasciato stasera?

Grazie per l'aiuto.

**Comment by Fredxp73** [comment]
Salve, anche a me fa la stessa cosa ......

**Comment by maatx** [comment]
urca, allora aspetto ad aggiornare alla 2024.7

**Comment by pietropola** [comment]
Confermo, dopo aver aggiornato stesso problema.
Son tornato alla versione precedente per il momento.

**Comment by pierpaolo1972** [comment]
Stesso problema

**Comment by maatx** [comment]
Ci sono novità?
Oggi è uscita la 2024.7.1

**Comment by FrancescoFdd5** [comment]
Anche con la 2024.7.1 stesso problema

**Comment by maatx** [comment]
Ci sono novità.
Con una semplice modifica a sensor.py si sitema e torna a funzionare

**Comment by FrancescoFdd5** [comment]
> Ci sono novità. Con una semplice modifica a sensor.py si sistema e torna a funzionare

ciao riesci a dire che modifica? E nel caso fare un pull request

**Comment by maatx** [comment]
non è farina del mio sacco. Mi ha aiutato mio figlio.
![image](https://github.com/wilds/hass-atonstorage/assets/4578794/325ef488-647e-4ec4-ab1f-f3e8d1cd0d43)

**Comment by FrancescoFdd5** [comment]
> non è farina del mio sacco. Mi ha aiutato mio figlio. ![image](https://private-user-images.githubusercontent.com/4578794/346286280-325ef488-647e-4ec4-ab1f-f3e8d1cd0d43.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyODM4NTIsIm5iZiI6MTcyMDI4MzU1MiwicGF0aCI6Ii80NTc4Nzk0LzM0NjI4NjI4MC0zMjVlZjQ4OC02NDdlLTRlYzQtYWIxZi1mM2U4ZDFjZDBkNDMuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA2VDE2MzIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3MDgyZmExYTk2OWFiOGZhZDg2ODgxOWFlYzAxMTM4YTkyN2VjNWE0YTdiZmZmNTk2OGEzMmQ5NjIyOWZmODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.22flS7an1-jVMDKmlnatOzU1__KbCAM0W970fcEE8Tw)

Confermo ora funziona,

Basta aggiungere 

max_sub_interval=None

Creo una pull request, ovviamente ringraziando te e tuo figlio :)

**Comment by FrancescoFdd5** [comment]
#35

**Comment by maatx** [comment]
è lui:

https://github.com/massimopavoni

**Comment by pierpaolo1972** [comment]
Intanto grazie, potete darmi più dettagli di dove trovo la riga da aggiungere o moficare?

**Comment by maatx** [comment]
> Intanto grazie, potete darmi più dettagli di dove trovo la riga da aggiungere o moficare?

guarda l'immagine che ho allegato

**Comment by pierpaolo1972** [comment]
si ok, ma dove la apro quella schermata?

**Comment by maatx** [comment]
quella è del mio programma di editing  ma puoi usare tranquillamente l'editor di Home Assistant

**Comment by Fredxp73** [comment]
Grazie mille, 
anche a me  ora funziona tutto come prima......

**Comment by pierpaolo1972** [comment]
C'ho messo un po' a trovare il sensor.py ma confermo che ora dopo la modifica funziona. Grazie mille

**Comment by FrancescoFdd5** [comment]
Aggiungo anche la trascrizione per utenti non italiani
I will also add the transcription for non-Italian users.

A user reported an issue with the AtonStorage integration in Home Assistant after a recent update, causing all variables to become "unavailable." The log indicates a TypeError related to a missing argument. Several users confirmed the same issue. A solution involved modifying `sensor.py` by adding `max_sub_interval=None`. This fix resolved the problem, and a pull request #35  was created to incorporate the change into the main codebase.

You can see the line to add in the pictures above.

**Comment by shadow107** [comment]
Grazie , anche io ho risolto il problema.
Volevo chiedere se fosse possibile visualizzare quanta energia in kWh è stata accumulata nella batteria e quanta ne è stata consumata giornalmente, al momento credo che faccia la somma in entrambi i casi da quando è attivo l’impianto . Visto che mi segna come carica oggi 1.2 Mwh. Grazie

**Comment by maatx** [comment]
>  Volevo chiedere se fosse possibile visualizzare quanta energia in kWh 

Penso basti moltiplicare _Battery charged current_   per _Battery voltage_  per ottenere il valore in Wh
