### ISSUE TITLE
Home Assistant Core update

### ISSUE THREAD

**Issue by Majikmonke** [wilds/hass-atonstorage#36]
Hi

I have noticed that I lose most entities (only have 7 remaining) when I update to the most recent.

This happened with update 7 and the 7.1 but was fine with all the 6.4 versions.

**Comment by FrancescoFdd5** [comment]
refer to #34

**Comment by Majikmonke** [comment]
I would but my Italian is not as good as my english

**Comment by FrancescoFdd5** [comment]
Hi, I have added an explanation in English of the issue and how to resolve it.

**Comment by Majikmonke** [comment]
Thank you



Kind regards

Dan Scate

Sent from my Samsung Galaxy smartphone.



-------- Original message --------
From: FrancescoFdd5 ***@***.***>
Date: 07/07/2024 10:22 (GMT+00:00)
To: wilds/hass-atonstorage ***@***.***>
Cc: Majikmonke ***@***.***>, Author ***@***.***>
Subject: Re: [wilds/hass-atonstorage] Home Assistant Core update (Issue #36)


Hi, I have added an explanation in English of the issue and how to resolve it.

**Comment by Majikmonke** [comment]
I still don't understand how to fix it. I don't seem to be able to find that entity to alter. I'm using Home Assistant Green through phone so perhaps that's the issue

**Comment by FrancescoFdd5** [comment]
You need to modify the plugin file. I don't know if you can do it from home assistant green. I hope the author approves the update soon

**Comment by Majikmonke** [comment]
Hi

I needed the add an add on but all now working.

Many thanks

Kind regards

Dan Scate

Sent from my Samsung Galaxy smartphone.



-------- Original message --------
From: FrancescoFdd5 ***@***.***>
Date: 08/07/2024 09:05 (GMT+00:00)
To: wilds/hass-atonstorage ***@***.***>
Cc: Majikmonke ***@***.***>, Author ***@***.***>
Subject: Re: [wilds/hass-atonstorage] Home Assistant Core update (Issue #36)


You need to modify the plugin file. I don't know if you can do it from home assistant green. I hope the author approves the update soon

**Comment by wilds** [comment]
duplicate #34
