### ISSUE TITLE
collegamento all inverter aton?

### ISSUE THREAD

**Issue by Fredxp73** [wilds/hass-atonstorage#6]
Ciao vorrei collegagare il mio inverter Aton (mstore ) all Home assistant(raspberry) che tipo di connessione devo eseguire tra i due?
grazie

**Comment by marcoCasamento** [comment]
Credo che non sia questo il posto per questo genere di assistenza, e questa integrazione non necessita di alcun collegamento "fisico" con l'inverter. Porrei la domanda sui forum di HA, dove potrebbe essere utile anche ad altri.
